# SOPS configuration for encrypted prompts
# See: https://github.com/getsops/sops
#
# Setup:
#   1. Install: brew install sops age
#   2. Generate key: age-keygen -o ~/.config/sops/age/keys.txt
#   3. Replace the placeholder below with your public key (age1...)
#   4. Set in .envrc: export SOPS_AGE_KEY_FILE="$HOME/.config/sops/age/keys.txt"
#   5. Create/edit: sops prompts/secret.yaml

creation_rules:
  # Encrypted prompts (all values encrypted)
  - path_regex: prompts/secret\.yaml$
    age: age1w9ggad5u74naq4nglacthcrzhgz7zygeeefrdfj78g23ugdhzqeqwjsnj2
    # ^^^ Replace with your age public key from: age-keygen

  # Encrypted results (only reasoning and answer fields encrypted)
  - path_regex: perf/encrypted_results\.yaml$
    age: age1w9ggad5u74naq4nglacthcrzhgz7zygeeefrdfj78g23ugdhzqeqwjsnj2
    # ^^^ Replace with your age public key from: age-keygen
    encrypted_regex: "^(reasoning|answer)$"
